refine c compiler checking

diff --git a/auto/cc/name b/auto/cc/name
--- a/auto/cc/name
+++ b/auto/cc/name
@@ -2,31 +2,21 @@
 # cc/name
 
 
-case $NM_PLATFORM in 
+nm_feature="C compiler"
+nm_feature_name=
+nm_feature_run=yes
+nm_feature_incs=
+nm_feature_path=
+nm_feature_libs=
+nm_feature_test=
+. ${NM_HOME}auto/feature
 
-	MSYS_NT:*)
-	;;
-
-	*)
-  	nm_feature="C compiler"
-  	nm_feature_name=
-  	nm_feature_run=yes
-  	nm_feature_incs=
-  	nm_feature_path=
-  	nm_feature_libs=
-  	nm_feature_test=
-  	. ${NM_HOME}auto/feature
-
-  	if [ ".$nm_found" = ".no" ]; then
-  	  echo
-  	  echo $0: error: C compiler $CC is not found
-  	  echo
-  	  exit 1
-  	fi
-	;;
-
-esac
-
+if [ ".$nm_found" = ".no" ]; then
+  #echo
+  echo " + $0: error: C compiler $CC is not found"
+  #echo
+  exit 1
+fi
 
 
 if `$CC -v 2>&1 | grep 'gcc version' >/dev/null 2>&1`; then
