friendly output for generating version,configure, and Makefile

diff --git a/auto/make b/auto/make
--- a/auto/make
+++ b/auto/make
@@ -138,6 +138,13 @@ make_stick_norm() {
 	fi
 }
 
+echo_ok_or_failed() {
+  if [ 0 -eq $1 ]; then
+    echo "ok"
+  else
+    echo "failed"
+  fi
+}
 
 # basic paths
 cat << END >> $NM_MAKEFILE
@@ -158,9 +165,11 @@ for stick in ${NM_HAS_STICKS[@]}; do
 	nm_stick_norm="`make_stick_norm $nm_src_stick $stick`"
 
 	if [ ! -d "$nm_src_stick" ]; then
+    
     if [ YES = $NM_NEW ]; then
-      echo " + creating $nm_src_stick directory ... "
+      echo $nm_n " + generating $nm_src_stick directory ... "
       mkdir -p $nm_src_stick
+      echo_ok_or_failed $?
       
     else
 		  echo " + checking for $nm_src_stick ... no found"
@@ -178,7 +187,8 @@ END
     have=`echo $nm_stick_norm | tr '[:lower:]' '[:upper:]'`_VERSION \
     value=`cat $nm_src_stick/version` . ${NM_HOME}auto/define
     
-  elif [ "YES" = "$NM_NEW" ]; then
+  elif [ YES = $NM_NEW ]; then
+    echo $nm_n " + generating $nm_src_stick/version file ... "
     cat << END > $nm_src_stick/version
 #!/bin/bash
 # generated by Nore
@@ -188,12 +198,15 @@ END
 # 0x201103
 
 END
-	fi # end of version
+    echo_ok_or_failed $?
+	fi # end of -f version
   
 	if [ -f $nm_src_stick/configure ]; then
 		echo " + checking for $nm_src_stick/configure ... found"
 		. $nm_src_stick/configure
-  elif [ "YES" = "$NM_NEW" ]; then
+    
+  elif [ YES = $NM_NEW ]; then
+		echo $nm_n " + generating $nm_src_stick/configure file ... "
     cat << END > $nm_src_stick/configure
 #!/bin/bash
 # generated by Nore
@@ -263,7 +276,8 @@ END
 #esac
 
 END
-	fi
+    echo_ok_or_failed $?
+	fi # end of -f configure
   
 	if [ -f $nm_src_stick/Makefile.$CC_NAME ]; then
 		stick_makefile=$nm_src_stick/Makefile.$CC_NAME
@@ -278,11 +292,12 @@ END
 		echo " + checking for $nm_src_stick/Makefile ... found"
 
   elif [ YES = $NM_NEW ]; then
-    echo " + generating for $nm_src_stick/Makefile ... "
-    cat << END > $nm_src_stick/Makefile
+    echo $nm_n " + generating $nm_src_stick/Makefile file ... "
+    cat << END > "$nm_src_stick/Makefile"
 #!/bin/bash
 # generated by Nore
-#
+# 
+# check $NM_MAKEFILE for details
 
 ${nm_stick_norm}_binout := \$(bin_path)${nm_stick_norm}\$(bin_ext)
 
@@ -294,6 +309,7 @@ ${nm_stick_norm}_test: ${nm_stick_norm}
 	\$(CC) \$(CFLAGS) \$(INC) \$< \$(bin_out)\$@
 
 END
+    echo_ok_or_failed $?
     
 	else
 
