improved unknown option and --has-* option

diff --git a/auto/options b/auto/options
--- a/auto/options
+++ b/auto/options
@@ -41,17 +41,26 @@ NM_CPU_CACHE_LINE=
 NM_HAS_STICKS=()
 
 
+legal_dir_reg='^[a-zA-Z_][a-zA-Z_0-9]*$'
+legal_has_opt='[a-zA-Z_][a-zA-Z_0-9]*$'
+
 legal_dir() {
-	[ "$@" = "`echo \"$@\" | tr -d '[\t :=]' 2>&1`" ]
+	echo "$@" | grep "${legal_dir_reg}" &>/dev/null
 }
 
 panic_arg() {
-	echo "!panic: invalid argument ${1}'${@:2}'"
+	echo "! panic: invalid argument ${1}'${@:2}'"
+	echo "  ${1} should be '${legal_dir_reg}'"
 	exit 1
 }
 
-panic_opt() {
-  echo "!panic: invalid option '$@'"
+legal_has_opt() {
+	echo "$@" | grep "\-\-has-${legal_has_opt}" &>/dev/null
+}
+
+panic_has_opt() {
+  echo "! panic: invalid option '$@'"
+	echo "  --has-* where * should be '${legal_dir_reg}'"
 	exit 1
 }
 
@@ -112,17 +121,20 @@ do
 		--with-verbose)          NM_VERBOSE=YES             	;;
 
 		--has-*)
-			if `legal_dir "$option"`; then
+			if `legal_has_opt "$option"`; then
 				NM_HAS_STICKS+=(`echo "$option" \
-					| sed -e 's/\ *--has-\([a-zA-Z][a-zA-Z]*\)/\1/' \
+					| sed -e "s/\ *--has-\(${legal_has_opt}\)/\1/" \
 					| tr '[:upper:]' '[:lower:]'`
 				)
 			else
-				panic_opt "$option"
+				panic_has_opt "$option"
 			fi
 			;;
     
-    *) panic_opt "$option" ;;
+    *)
+			echo "! panic: unkown option '$option'"
+			exit 1
+			;;
   esac
 done
 
